## Github workflow to create multiarch binaries from source
name: Create Binaries

inputs:
  arch:
    description: "Architecture to build binary for"
    required: true
    type: string
  tag:
    description: "Release Tag"
    required: false
    type: string

runs:
  using: "composite"
  steps:
    ## Setup Docker for the builds
    - name: Docker setup
      uses: stacks-network/actions/docker@main

    ## Build the binaries using defined dockerfiles
    - name: Build Binary (${{ inputs.arch }})
      id: build_binaries
      uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # 5.1.0
      with:
        file: build-scripts/Dockerfile.${{ inputs.arch }}
        outputs: type=local,dest=./release/${{ inputs.arch }}
        build-args: |
          STACKS_NODE_VERSION=${{ inputs.tag || env.GITHUB_SHA_SHORT }}
          OS_ARCH=${{ inputs.arch }}
          GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
          GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}

    ## Compress the binary artifact
    - name: Compress artifact
      id: compress_artifact
      shell: bash
      run: zip --junk-paths ${{ inputs.arch }} ./release/${{ inputs.arch }}/*

    ## Upload the binary artifact to the github action
    - name: Upload artifact
      id: upload_artifact
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        path: ${{ inputs.arch }}.zip
