## Github workflow to create multiarch binaries from source
name: Create Binaries

inputs:
  arch:
    description: "Stringified JSON object of platform matrix"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    ## Setup Docker for the builds
    - name: Docker setup
      uses: stacks-network/actions/docker@main

    ## Git checkout the actions repository
    - name: Checkout actions
      id: checkout_actions
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: BowTiedDevOps/actions
        path: actions-repo
        ref: feat/move-binary-build-to-composite

    - name: List
      shell: bash
      run: |
        ls
        echo "------"
        ls actions-repo/stacks-core/create-source-binary/build-scripts

    ## Build the binaries using defined dockerfiles
    - name: Build Binary (${{ inputs.arch }})
      id: build_binaries
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # 5.0.0
      with:
        file: actions-repo/stacks-core/create-source-binary/build-scripts/Dockerfile.${{ inputs.arch }}
        outputs: type=local,dest=./release/${{ inputs.arch }}
        build-args: |
          STACKS_NODE_VERSION=${{ inputs.tag || env.GITHUB_SHA_SHORT }}
          OS_ARCH=${{ inputs.arch }}
          GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
          GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}

    ## Compress the binary artifact
    - name: Compress artifact
      id: compress_artifact
      shell: bash
      run: zip --junk-paths ${{ inputs.arch }} ./release/${{ inputs.arch }}/*

    ## Upload the binary artifact to the github action (used in `github-release.yml` to create a release)
    - name: Upload artifact
      id: upload_artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        path: ${{ inputs.arch }}.zip
