## Github workflow to generate a sha512 checksum for the build archive
name: Generate Checksum

inputs:
  hashfile_name:
    description: "The name of the generated checksum file"
    required: false
    default: "CHECKSUMS.txt"
  artifact_name:
    description: "Download artifacts starting with this name"
    required: false
    default: "*"

runs:
  using: "composite"
  steps:
    ## Downloads the artifacts from the workflow starting with 'artifact_name' input
    - name: Download Artifacts
      id: download_artifacts
      uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
      with:
        pattern: ${{ inputs.artifact_name }}
        merge-multiple: 'true'
        path: artifacts

    ## Generate a checksums file
    - name: Generate Checksums
      id: generate_checksum
      shell: bash
      run: |
        # If sha512sum command doesn't exist on the host, exit
        if ! command -v sha512sum > /dev/null 2>&1; then
          echo "sha512sum command doesn't exist!";
          exit 1;
        fi

        # Generate the hashes and exit if the variable is empty
        shasum="$(sha512sum artifacts/*)"
        if [[ -z "$shasum" ]]; then
          echo "Checksum could not be generated!";
          exit 1;
        fi

        echo "Generated checksums:"
        echo "$shasum"
        echo "$shasum" > "${{ inputs.hashfile_name }}";
        exit 0;
