## Github workflow to check that all jobs parsed as input from 'needs' are successful
name: Check Jobs Status

inputs:
  jobs:
    description: "A list of jobs from the `needs` context."
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Jobs
      id: check_jobs
      shell: bash
      run: |
        # Check the jobs status and print the failures to step summary
        are_jobs_successful=true

        # Check that 'jq' command exists
        if ! command -v jq > /dev/null 2>&1; then
          echo "jq command doesn't exist!";
          exit 1;
        fi

        # Print all jobs
        echo '${{ inputs.jobs }}'

        # Search for failures and append them to a list
        for job_name in $(echo '${{ inputs.jobs }}' | jq -r 'keys[]'); do
          result=$(echo '${{ inputs.jobs }}' | jq -r ".[\"$job_name\"].result")
          if [[ "$result" == "failure" ]]; then
            echo "$job_name failed!"
            are_jobs_successful=false
          fi
        done

        echo "All jobs were successful!"
        exit 0
