## Github workflow to check that all jobs parsed as input from 'needs' are successful
name: Check Jobs Result

inputs:
  jobs:
    description: "A list of jobs from the `needs` context."
    required: true

runs:
  using: "composite"
  steps:
    - name: Print needs content
      id: print_needs
      shell: bash
      run: |
        for job_name in $(echo '${{ inputs.jobs }}' | jq -r 'keys[]'); do
          result=$(echo '${{ inputs.jobs }}' | jq -r ".[\"$job_name\"].result")
          if [[ "$result" == "failure" ]]; then
            echo "$job_name failed!"
            exit 1
        done

        echo "All jobs were successful!"
        exit 0
