## Github workflow to generate a sha512 checksum for the build archive
name: Generate Checksum

inputs:
  jobs:
    description: "A list of jobs from the `needs` context."
    required: true

runs:
  using: "composite"
  steps:
    - name: Print needs content
      id: print_needs
      shell: bash
      run: |
        echo "${{ inputs.jobs }}"
        for job_name in $(echo "${{ inputs.jobs }}" | jq -r 'keys[]'); do
          result=$(echo "${json_data}" | jq -r ".${job_name}.result")
          echo "Job ${job_name} result: ${result}"
        done
