## Github workflow to check that all jobs parsed as input from 'needs' are successful
name: Check Jobs Result

inputs:
  jobs:
    description: "A list of jobs from the `needs` context."
    required: true

runs:
  using: "composite"
  steps:
    - name: Print needs content
      id: print_needs
      shell: bash
      run: |
        echo "${{ inputs.jobs }}"
        for job_name in $(echo "${{ inputs.jobs }}" | jq -r 'keys[]'); do
          result=$(echo "${{ inputs.jobs }}" | jq -r ".${job_name}.result")
          echo "Job ${job_name} result: ${result}"
        done
