## Github workflow to generate a sha512 checksum for the build archive
name: Generate Checksum

inputs:
  jobs:
    description: "A list of jobs from the `needs` context."
    required: true

runs:
  using: "composite"
  steps:
    - name: Print needs content
      id: print_needs
      shell: bash
      run: |
        echo ${{ inputs.jobs }}
        job_needs=${{ fromJson(inputs.jobs) }}
        echo $job_needs
        for job in "${jobs_needs[@]}"; do
          echo $job
          job_status=$(echo "$job_needs.$job.outputs.status" | tr -d '"')
          echo $job_status
          if [ "$job_status" != "success" ]; then
            echo "Job $job failed or has not completed successfully."
            exit 1
          fi
        done

        echo "All previous jobs are successful."
